FROM ubuntu:20.04
WORKDIR /mongo_shard1_server
RUN mkdir -p /mongo_shard1_server/SHARED_DIR
RUN  apt-get update \
  && apt-get install -y wget
COPY ./install_mongodb.sh /mongo_shard1_server
COPY ./auth_keyfile_for_cluster.key /mongo_shard1_server
RUN /mongo_shard1_server/install_mongodb.sh
COPY ./bash_script_Shard1_Server_Master_CONFIG.sh /mongo_shard1_server
COPY ./bash_script_Shard1_Server_Master_CMD.sh /mongo_shard1_server
COPY ./rootCA.pem /etc/ssl
COPY ./mongodb.pem /etc/ssl
RUN /mongo_shard1_server/bash_script_Shard1_Server_Master_CONFIG.sh
CMD /mongo_shard1_server/bash_script_Shard1_Server_Master_CMD.sh
