#!/bin/bash
#This is comment

MONGO_SHARD2_SERVER_MASTER_IP_ADDR=172.17.0.1
MONGO_SHARD2_SERVER_MASTER_PORT=27007
MONGO_SHARD2_SERVER_SLAVE1_IP_ADDR=172.17.0.1
MONGO_SHARD2_SERVER_SLAVE1_PORT=27008
MONGO_SHARD2_SERVER_SLAVE2_IP_ADDR=172.17.0.1
MONGO_SHARD2_SERVER_SLAVE2_PORT=27009

MONGO_ROUTER_SERVER_IP_ADDR=172.17.0.1
MONGO_ROUTER_SERVER_PORT=27010

REDIRECT_STDERR_TO_STDOUT="2>&1"
OUTPUT_FILE="/mongo_shard2_server/SHARED_DIR/BASH_SCRIPT_FROM_SHARD2_SERVER_MASTER.txt"
REDIRECT_STDOUT_TO_OUTFILE=" > ${OUTPUT_FILE}"
FULL_REDIRECT_COMMAND=${REDIRECT_STDERR_TO_STDOUT}${REDIRECT_STDOUT_TO_OUTFILE}

mongod --config /etc/mongod.conf & 
sleep 20 
CONFIG_REPLIC_SET="rs.initiate({_id: \"shard2\", members: [{_id: 0, host: \"$MONGO_SHARD2_SERVER_MASTER_IP_ADDR:$MONGO_SHARD2_SERVER_MASTER_PORT\", priority: 2}, {_id: 1, host: \"$MONGO_SHARD2_SERVER_SLAVE1_IP_ADDR:$MONGO_SHARD2_SERVER_SLAVE1_PORT\"}, {_id: 2, host: \"$MONGO_SHARD2_SERVER_SLAVE2_IP_ADDR:$MONGO_SHARD2_SERVER_SLAVE2_PORT\"}]})"
REPLICA_SET_STATUS="rs.status()"
TLS_PARAMETRS_FOR_MONGO_SHELL="--tls --host 127.0.0.1 --port 27017 --tlsCertificateKeyFile /etc/ssl/mongodb.pem --tlsCAFile /etc/ssl/rootCA.pem"
echo -e ${CONFIG_REPLIC_SET}\\n${REPLICA_SET_STATUS} | mongo ${TLS_PARAMETRS_FOR_MONGO_SHELL} > ${OUTPUT_FILE} ${REDIRECT_STDERR_TO_STDOUT}
sleep infinity
